//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WCFDbEntities : DbContext
    {
        public WCFDbEntities()
            : base("name=WCFDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
         
         //   throw new UnintentionalCodeFirstException();
        } 
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<type_client> type_client { get; set; }
    }
}
